site_name: Siddhi-IO-TCP
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO TCP: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.2-SNAPSHOT: api/4.0.2-SNAPSHOT.md
theme: material
